# Generated by Django 5.1.3 on 2024-11-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antrian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('umur', models.PositiveIntegerField()),
                ('nomor_hp', models.CharField(max_length=15)),
                ('poli', models.CharField(choices=[('anak', 'Poli Anak'), ('umum', 'Poli Umum')], max_length=10)),
                ('waktu_daftar', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
