# Generated by Django 5.1.3 on 2024-11-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puskesmas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antrian',
            name='waktu_daftar',
        ),
        migrations.AddField(
            model_name='antrian',
            name='selesai',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='antrian',
            name='nama',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='antrian',
            name='nomor_hp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='antrian',
            name='poli',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='antrian',
            name='umur',
            field=models.IntegerField(),
        ),
    ]
